// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqmrolbtmfiximvufgdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbXJvbGJ0bWZpeGltdnVmZ2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDMzMjEsImV4cCI6MjA2NDQxOTMyMX0.A9vyGChx9n5ZPbTQzyagWkmEydZHDDW_qc-tQJPkHl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);